### PR TITLE
First commit for gallery-timeline

### PR DESCRIPTION
**Pull request by Satyam**

### CODE REVIEW

**Comment by davglass** [comment]
Pull requests for Gallery modules are not allowed on GitHub, you need to submit a "CDN Request" from your modules page on the Gallery.

**Comment by Satyam** [comment]
Done. I didn't quite remember how it went.  I have a vague memory of EricF talking about doing pull requests from GitHub, but don't remember what for.  

Thanks.

**Comment by foxxtrot** [comment]
Modifications to Core are being handled with github pull requests now.

**Comment by davglass** [comment]
@Satyam I don't see it in the queue.

Visit your modules page: http://yuilibrary.com/gallery/show/timeline

Then click the CDN Request button, select the commit you want pulled in the build and submit your request.

I'll be doing the Gallery build tomorrow at 3pm CST.

**Pull request closed without merging**
